// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getLeslie
arma::mat getLeslie(const arma::mat& Surv, const arma::mat& Fec, const double& SRB);
RcppExport SEXP _ReDDLeslie_getLeslie(SEXP SurvSEXP, SEXP FecSEXP, SEXP SRBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Surv(SurvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Fec(FecSEXP);
    Rcpp::traits::input_parameter< const double& >::type SRB(SRBSEXP);
    rcpp_result_gen = Rcpp::wrap(getLeslie(Surv, Fec, SRB));
    return rcpp_result_gen;
END_RCPP
}
// ProjectHarvest
arma::mat ProjectHarvest(const arma::mat& Surv, const arma::mat& Harvpar, const arma::mat& Fec, const arma::mat& SRB, const List& aK0, const bool& global, const bool& null, const arma::mat& bl, const int& period, const IntegerVector& nage);
RcppExport SEXP _ReDDLeslie_ProjectHarvest(SEXP SurvSEXP, SEXP HarvparSEXP, SEXP FecSEXP, SEXP SRBSEXP, SEXP aK0SEXP, SEXP globalSEXP, SEXP nullSEXP, SEXP blSEXP, SEXP periodSEXP, SEXP nageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Surv(SurvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Harvpar(HarvparSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Fec(FecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SRB(SRBSEXP);
    Rcpp::traits::input_parameter< const List& >::type aK0(aK0SEXP);
    Rcpp::traits::input_parameter< const bool& >::type global(globalSEXP);
    Rcpp::traits::input_parameter< const bool& >::type null(nullSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bl(blSEXP);
    Rcpp::traits::input_parameter< const int& >::type period(periodSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type nage(nageSEXP);
    rcpp_result_gen = Rcpp::wrap(ProjectHarvest(Surv, Harvpar, Fec, SRB, aK0, global, null, bl, period, nage));
    return rcpp_result_gen;
END_RCPP
}
// getAerialCount
arma::mat getAerialCount(const arma::mat& Harv, const arma::mat& H, const arma::mat& A);
RcppExport SEXP _ReDDLeslie_getAerialCount(SEXP HarvSEXP, SEXP HSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Harv(HarvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(getAerialCount(Harv, H, A));
    return rcpp_result_gen;
END_RCPP
}
// eyes
arma::mat eyes(int n);
RcppExport SEXP _ReDDLeslie_eyes(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(eyes(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ReDDLeslie_getLeslie", (DL_FUNC) &_ReDDLeslie_getLeslie, 3},
    {"_ReDDLeslie_ProjectHarvest", (DL_FUNC) &_ReDDLeslie_ProjectHarvest, 10},
    {"_ReDDLeslie_getAerialCount", (DL_FUNC) &_ReDDLeslie_getAerialCount, 3},
    {"_ReDDLeslie_eyes", (DL_FUNC) &_ReDDLeslie_eyes, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ReDDLeslie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
