# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getLeslie <- function(Surv, Fec, SRB) {
    .Call(`_ReDDLeslie_getLeslie`, Surv, Fec, SRB)
}

ProjectHarvestCpp <- function(Surv, Harvpar, Fec, SRB, aK0, global, null, bl, period, nage) {
    .Call(`_ReDDLeslie_ProjectHarvestCpp`, Surv, Harvpar, Fec, SRB, aK0, global, null, bl, period, nage)
}

getAerialCount <- function(Harv, H, A) {
    .Call(`_ReDDLeslie_getAerialCount`, Harv, H, A)
}

eyes <- function(n) {
    .Call(`_ReDDLeslie_eyes`, n)
}

