# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getLeslie <- function(Surv, Fec, SRB) {
    .Call(`_ReCAP_getLeslie`, Surv, Fec, SRB)
}

ProjectAllCpp <- function(Surv, Harvpar, Fec, SRB, aK0, global, null, bl, period, nage) {
    .Call(`_ReCAP_ProjectAllCpp`, Surv, Harvpar, Fec, SRB, aK0, global, null, bl, period, nage)
}

getAerialCountPost <- function(Proj, obsMat, A) {
    .Call(`_ReCAP_getAerialCountPost`, Proj, obsMat, A)
}

getAerialCountPre <- function(Proj, obsMat, A) {
    .Call(`_ReCAP_getAerialCountPre`, Proj, obsMat, A)
}

getobsVitals <- function(vital, living, obsMat) {
    .Call(`_ReCAP_getobsVitals`, vital, living, obsMat)
}

get_obs_LambdasA <- function(Living_total) {
    .Call(`_ReCAP_get_obs_LambdasA`, Living_total)
}

get_hypo_Lambdas_helper <- function(Harv_n, living, H_n, Surv_np1, Fec_np1, SRB_np1, H_np1) {
    .Call(`_ReCAP_get_hypo_Lambdas_helper`, Harv_n, living, H_n, Surv_np1, Fec_np1, SRB_np1, H_np1)
}

get_hypo_harvest_quotaCpp <- function(bl, Harv, Surv, Fec, SRB, harv_weight, global, aK0, null) {
    .Call(`_ReCAP_get_hypo_harvest_quotaCpp`, bl, Harv, Surv, Fec, SRB, harv_weight, global, aK0, null)
}

get_hypo_harvest_portionCpp <- function(bl, Harv_rate, Surv, Fec, SRB, harv_weight, global, aK0, null, period, nage) {
    .Call(`_ReCAP_get_hypo_harvest_portionCpp`, bl, Harv_rate, Surv, Fec, SRB, harv_weight, global, aK0, null, period, nage)
}

get_hypo_harvest_quota_simpleDD_Cpp <- function(living_obs, Harv, Surv, Fec, SRB, harv_weight, K) {
    .Call(`_ReCAP_get_hypo_harvest_quota_simpleDD_Cpp`, living_obs, Harv, Surv, Fec, SRB, harv_weight, K)
}

get_hypo_harvest_portion_simpleDD_Cpp <- function(bl, living_obs, Harv_rate, Surv, Fec, SRB, harv_weight, nage, period, K) {
    .Call(`_ReCAP_get_hypo_harvest_portion_simpleDD_Cpp`, bl, living_obs, Harv_rate, Surv, Fec, SRB, harv_weight, nage, period, K)
}

get_hypo_Lambdas <- function(Harvest, Living, Harvpar, Surv, Fec, SRB) {
    .Call(`_ReCAP_get_hypo_Lambdas`, Harvest, Living, Harvpar, Surv, Fec, SRB)
}

eyes <- function(n) {
    .Call(`_ReCAP_eyes`, n)
}

